[2025-04-16T18:26:24.828+0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-16T18:26:24.841+0300] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: executing_Python_pipeline.read_csv_task manual__2025-04-16T15:26:21.425317+00:00 [queued]>
[2025-04-16T18:26:24.846+0300] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: executing_Python_pipeline.read_csv_task manual__2025-04-16T15:26:21.425317+00:00 [queued]>
[2025-04-16T18:26:24.847+0300] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-16T18:26:24.862+0300] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): read_csv_task> on 2025-04-16 15:26:21.425317+00:00
[2025-04-16T18:26:24.865+0300] {standard_task_runner.py:72} INFO - Started process 219682 to run task
[2025-04-16T18:26:24.869+0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'executing_Python_pipeline', 'read_csv_task', 'manual__2025-04-16T15:26:21.425317+00:00', '--job-id', '168', '--raw', '--subdir', 'DAGS_FOLDER/execute_python_pipeline.py', '--cfg-path', '/tmp/tmpa622fg15']
[2025-04-16T18:26:24.871+0300] {standard_task_runner.py:105} INFO - Job 168: Subtask read_csv_task
[2025-04-16T18:26:24.910+0300] {task_command.py:467} INFO - Running <TaskInstance: executing_Python_pipeline.read_csv_task manual__2025-04-16T15:26:21.425317+00:00 [running]> on host DESKTOP-1SBO1JU.
[2025-04-16T18:26:24.976+0300] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='tasneemahmed' AIRFLOW_CTX_DAG_ID='executing_Python_pipeline' AIRFLOW_CTX_TASK_ID='read_csv_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-16T15:26:21.425317+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-16T15:26:21.425317+00:00'
[2025-04-16T18:26:24.977+0300] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-16T18:26:24.997+0300] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/tasneemahmed24/airflow/dags/execute_python_pipeline.py", line 19, in read_csv_file
    df = pd.read_csv('/home/tasneemahmed24/airflow/dags/insurance.csv')
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/home/tasneemahmed24/airflow/dags/insurance.csv'
[2025-04-16T18:26:25.004+0300] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=executing_Python_pipeline, task_id=read_csv_task, run_id=manual__2025-04-16T15:26:21.425317+00:00, execution_date=20250416T152621, start_date=20250416T152624, end_date=20250416T152625
[2025-04-16T18:26:25.033+0300] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-16T18:26:25.034+0300] {standard_task_runner.py:124} ERROR - Failed to execute job 168 for task read_csv_task ([Errno 2] No such file or directory: '/home/tasneemahmed24/airflow/dags/insurance.csv'; 219682)
Traceback (most recent call last):
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/tasneemahmed24/airflow/dags/execute_python_pipeline.py", line 19, in read_csv_file
    df = pd.read_csv('/home/tasneemahmed24/airflow/dags/insurance.csv')
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/home/tasneemahmed24/airflow/dags/insurance.csv'
[2025-04-16T18:26:25.058+0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-16T18:26:25.074+0300] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-16T18:26:25.075+0300] {local_task_job_runner.py:245} INFO - ::endgroup::
