[2025-04-16T16:50:08.025+0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-16T16:50:08.037+0300] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: executing_Python_Branching_tasks_with_Backfill.branch_task manual__2025-04-16T13:50:02.927321+00:00 [queued]>
[2025-04-16T16:50:08.044+0300] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: executing_Python_Branching_tasks_with_Backfill.branch_task manual__2025-04-16T13:50:02.927321+00:00 [queued]>
[2025-04-16T16:50:08.044+0300] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-16T16:50:08.057+0300] {taskinstance.py:2890} INFO - Executing <Task(BranchPythonOperator): branch_task> on 2025-04-16 13:50:02.927321+00:00
[2025-04-16T16:50:08.059+0300] {standard_task_runner.py:72} INFO - Started process 179460 to run task
[2025-04-16T16:50:08.062+0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'executing_Python_Branching_tasks_with_Backfill', 'branch_task', 'manual__2025-04-16T13:50:02.927321+00:00', '--job-id', '156', '--raw', '--subdir', 'DAGS_FOLDER/execute_cron_catchup_backfill.py', '--cfg-path', '/tmp/tmpue5lvt30']
[2025-04-16T16:50:08.064+0300] {standard_task_runner.py:105} INFO - Job 156: Subtask branch_task
[2025-04-16T16:50:08.096+0300] {task_command.py:467} INFO - Running <TaskInstance: executing_Python_Branching_tasks_with_Backfill.branch_task manual__2025-04-16T13:50:02.927321+00:00 [running]> on host DESKTOP-1SBO1JU.
[2025-04-16T16:50:08.143+0300] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='tasneemahmed' AIRFLOW_CTX_DAG_ID='executing_Python_Branching_tasks_with_Backfill' AIRFLOW_CTX_TASK_ID='branch_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-16T13:50:02.927321+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-16T13:50:02.927321+00:00'
[2025-04-16T16:50:08.144+0300] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-16T16:50:08.153+0300] {baseoperator.py:423} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-04-16T16:50:08.157+0300] {python.py:240} INFO - Done. Returned value was: task_d
[2025-04-16T16:50:08.157+0300] {branch.py:38} INFO - Branch into task_d
[2025-04-16T16:50:08.158+0300] {skipmixin.py:233} INFO - Following branch ('task_d',)
[2025-04-16T16:50:08.160+0300] {skipmixin.py:281} INFO - Skipping tasks [('task_c', -1)]
[2025-04-16T16:50:08.180+0300] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-16T16:50:08.180+0300] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=executing_Python_Branching_tasks_with_Backfill, task_id=branch_task, run_id=manual__2025-04-16T13:50:02.927321+00:00, execution_date=20250416T135002, start_date=20250416T135008, end_date=20250416T135008
[2025-04-16T16:50:08.202+0300] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-16T16:50:08.212+0300] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-16T16:50:08.216+0300] {local_task_job_runner.py:245} INFO - ::endgroup::
