[2025-04-16T13:31:12.067+0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-16T13:31:12.082+0300] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: executing_sqlite_pipeline.delete_data manual__2025-04-16T10:31:03.439454+00:00 [queued]>
[2025-04-16T13:31:12.088+0300] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: executing_sqlite_pipeline.delete_data manual__2025-04-16T10:31:03.439454+00:00 [queued]>
[2025-04-16T13:31:12.089+0300] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-16T13:31:12.103+0300] {taskinstance.py:2890} INFO - Executing <Task(SqliteOperator): delete_data> on 2025-04-16 10:31:03.439454+00:00
[2025-04-16T13:31:12.105+0300] {standard_task_runner.py:72} INFO - Started process 97037 to run task
[2025-04-16T13:31:12.110+0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'executing_sqlite_pipeline', 'delete_data', 'manual__2025-04-16T10:31:03.439454+00:00', '--job-id', '119', '--raw', '--subdir', 'DAGS_FOLDER/sql_operators.py', '--cfg-path', '/tmp/tmpc092uq7n']
[2025-04-16T13:31:12.111+0300] {standard_task_runner.py:105} INFO - Job 119: Subtask delete_data
[2025-04-16T13:31:12.143+0300] {task_command.py:467} INFO - Running <TaskInstance: executing_sqlite_pipeline.delete_data manual__2025-04-16T10:31:03.439454+00:00 [running]> on host DESKTOP-1SBO1JU.
[2025-04-16T13:31:12.231+0300] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='tasneemahmed' AIRFLOW_CTX_DAG_ID='executing_sqlite_pipeline' AIRFLOW_CTX_TASK_ID='delete_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-16T10:31:03.439454+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-16T10:31:03.439454+00:00'
[2025-04-16T13:31:12.232+0300] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-16T13:31:12.248+0300] {sql.py:266} INFO - Executing: 
        DELETE FROM users WHERE is_active = False;
        
[2025-04-16T13:31:12.254+0300] {base.py:84} INFO - Retrieving connection 'my_sqlite_conn'
[2025-04-16T13:31:12.283+0300] {base.py:84} INFO - Retrieving connection 'my_sqlite_conn'
[2025-04-16T13:31:12.284+0300] {sql.py:542} INFO - Running statement: 
        DELETE FROM users WHERE is_active = False;
        , parameters: None
[2025-04-16T13:31:12.285+0300] {sql.py:551} INFO - Rows affected: 1
[2025-04-16T13:31:12.297+0300] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-16T13:31:12.298+0300] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=executing_sqlite_pipeline, task_id=delete_data, run_id=manual__2025-04-16T10:31:03.439454+00:00, execution_date=20250416T103103, start_date=20250416T103112, end_date=20250416T103112
[2025-04-16T13:31:12.365+0300] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-16T13:31:12.385+0300] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-16T13:31:12.390+0300] {local_task_job_runner.py:245} INFO - ::endgroup::
