[2025-04-17T10:33:37.026+0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-17T10:33:37.033+0300] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: executing_Python_Branching_tasks_with_Backfill.task_choice scheduled__2025-04-16T12:00:00+00:00 [queued]>
[2025-04-17T10:33:37.038+0300] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: executing_Python_Branching_tasks_with_Backfill.task_choice scheduled__2025-04-16T12:00:00+00:00 [queued]>
[2025-04-17T10:33:37.038+0300] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-17T10:33:37.048+0300] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): task_choice> on 2025-04-16 12:00:00+00:00
[2025-04-17T10:33:37.050+0300] {standard_task_runner.py:72} INFO - Started process 239961 to run task
[2025-04-17T10:33:37.054+0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'executing_Python_Branching_tasks_with_Backfill', 'task_choice', 'scheduled__2025-04-16T12:00:00+00:00', '--job-id', '186', '--raw', '--subdir', 'DAGS_FOLDER/execute_cron_catchup_backfill.py', '--cfg-path', '/tmp/tmp99cir12a']
[2025-04-17T10:33:37.055+0300] {standard_task_runner.py:105} INFO - Job 186: Subtask task_choice
[2025-04-17T10:33:37.085+0300] {task_command.py:467} INFO - Running <TaskInstance: executing_Python_Branching_tasks_with_Backfill.task_choice scheduled__2025-04-16T12:00:00+00:00 [running]> on host DESKTOP-1SBO1JU.
[2025-04-17T10:33:37.164+0300] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='tasneemahmed' AIRFLOW_CTX_DAG_ID='executing_Python_Branching_tasks_with_Backfill' AIRFLOW_CTX_TASK_ID='task_choice' AIRFLOW_CTX_EXECUTION_DATE='2025-04-16T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-16T12:00:00+00:00'
[2025-04-17T10:33:37.167+0300] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-17T10:33:37.182+0300] {python.py:240} INFO - Done. Returned value was: False
[2025-04-17T10:33:37.199+0300] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-17T10:33:37.200+0300] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=executing_Python_Branching_tasks_with_Backfill, task_id=task_choice, run_id=scheduled__2025-04-16T12:00:00+00:00, execution_date=20250416T120000, start_date=20250417T073337, end_date=20250417T073337
[2025-04-17T10:33:37.269+0300] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-17T10:33:37.284+0300] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-17T10:33:37.289+0300] {local_task_job_runner.py:245} INFO - ::endgroup::
