[2025-04-17T15:00:45.346+0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-17T15:00:45.355+0300] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: executing_Python_pipeline_using_variable.branching_task manual__2025-04-17T12:00:39.847503+00:00 [queued]>
[2025-04-17T15:00:45.361+0300] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: executing_Python_pipeline_using_variable.branching_task manual__2025-04-17T12:00:39.847503+00:00 [queued]>
[2025-04-17T15:00:45.361+0300] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-17T15:00:45.371+0300] {taskinstance.py:2890} INFO - Executing <Task(BranchPythonOperator): branching_task> on 2025-04-17 12:00:39.847503+00:00
[2025-04-17T15:00:45.375+0300] {standard_task_runner.py:72} INFO - Started process 358342 to run task
[2025-04-17T15:00:45.378+0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'executing_Python_pipeline_using_variable', 'branching_task', 'manual__2025-04-17T12:00:39.847503+00:00', '--job-id', '215', '--raw', '--subdir', 'DAGS_FOLDER/execute_branching_using_variable.py', '--cfg-path', '/tmp/tmphaze0jiw']
[2025-04-17T15:00:45.380+0300] {standard_task_runner.py:105} INFO - Job 215: Subtask branching_task
[2025-04-17T15:00:45.409+0300] {task_command.py:467} INFO - Running <TaskInstance: executing_Python_pipeline_using_variable.branching_task manual__2025-04-17T12:00:39.847503+00:00 [running]> on host DESKTOP-1SBO1JU.
[2025-04-17T15:00:45.453+0300] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='tasneemahmed' AIRFLOW_CTX_DAG_ID='executing_Python_pipeline_using_variable' AIRFLOW_CTX_TASK_ID='branching_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-17T12:00:39.847503+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-17T12:00:39.847503+00:00'
[2025-04-17T15:00:45.453+0300] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-17T15:00:45.462+0300] {baseoperator.py:423} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-04-17T15:00:45.467+0300] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 274, in execute
    return self.do_branch(context, super().execute(context))
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/tasneemahmed24/airflow/dags/execute_branching_using_variable.py", line 48, in branching
    if transform.startWith('filter'):
AttributeError: 'str' object has no attribute 'startWith'
[2025-04-17T15:00:45.470+0300] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=executing_Python_pipeline_using_variable, task_id=branching_task, run_id=manual__2025-04-17T12:00:39.847503+00:00, execution_date=20250417T120039, start_date=20250417T120045, end_date=20250417T120045
[2025-04-17T15:00:45.487+0300] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-17T15:00:45.488+0300] {standard_task_runner.py:124} ERROR - Failed to execute job 215 for task branching_task ('str' object has no attribute 'startWith'; 358342)
Traceback (most recent call last):
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 274, in execute
    return self.do_branch(context, super().execute(context))
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/tasneemahmed24/airflow/dags/execute_branching_using_variable.py", line 48, in branching
    if transform.startWith('filter'):
AttributeError: 'str' object has no attribute 'startWith'
[2025-04-17T15:00:45.520+0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-17T15:00:45.534+0300] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-17T15:00:45.542+0300] {local_task_job_runner.py:245} INFO - ::endgroup::
